#addons:
    #apt:
        #sources:
            #- llvm-toolchain-precise-3.7
        #packages:
            #- clang-3.7
language: cpp
sudo: required
dist: trusty
compiler:
    - clang
    - gcc
os:
    - linux
    - osx
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx"   && "CXX" == "clang++" ]];  then brew update                                                                                ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "CXX" == "clang++" ]];  then sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.8 main' ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "CXX" == "g++" ]];      then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y                                     ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]];                        then sudo apt-get update -q                                                                     ; fi
install:
    #- if [[ "$TRAVIS_OS_NAME" == "osx"   ] && ["CXX" == "clang++"]]; then brew install clang3.8 ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx"   && "CXX" == "g++" ]];      then brew install gcc5                                                                          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "CXX" == "clang++" ]];  then sudo apt-get install clang-3.8 -y                                                          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "CXX" == "g++" ]];      then sudo apt-get install gcc-5 g++-5 -y                                                        ; fi
    - if [[ "$CXX" = "g++" ]];                                      then export CXX="g++-5" CC="gcc-5"                                                              ; fi
    - if [[ "$CXX" = "clang++" ]];                                  then export CXX="clang++-3.7" CC="clang-3.7"                                                    ; fi
before_script:
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=release ..
script:
    - make
    - make test
