sudo: required
dist: trusty
language: cpp
compiler:
    - clang
    - gcc
os:
    - linux
    - osx
before_script:
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=release ..
script: make
