version: '1.0.{build}'
install:
    - mkdir build
    - cd build
    - if [[ "%platform%" == "x64" ]];   then cmake -G "Visual Studio 14 2015 Win64" ..  ; fi
    - if [[ "%platform%" == "Win32" ]]; then cmake -G "Visual Studio 14 2015" ..        ; fi
    - cd ..
build_script:
    - msbuild "build//DEFAULT_PROJECT.sln"
branches:
    except:
        - gh-pages
configuration:
    - Debug
    - Release
platform:
    - Win32
    - x64
matrix:
    fast_finish: false
build:
    parallel: true                          # enable MSBuild parallel builds
    project: "build/DEFAULT_PROJECT.sln"    # path to Visual Studio solution or project
