version: '1.0.{build}'
install:
    - mkdir build
    - cd build
    - cmake ..
    - cd ..
build_script:
    - cmd msbuild "build//DEFAULT_PROJECT.sln" /p:Configuration=$CONFIGURATION /p:Platform=$PLATFORM
branches:
    except:
        - gh-pages
configuration:
    - Debug
    - Release
platform:
    - Win32
    - x64
matrix:
    fast_finish: false
build:
    parallel: true                          # enable MSBuild parallel builds
    project: "build/DEFAULT_PROJECT.sln"    # path to Visual Studio solution or project
