version: '1.0.{build}'
install:
    - cmake -DCMAKE_BUILD_TYPE=release .
    - msbuild DEFAULT_PROJECT.sln
branches:
    except:
        - gh-pages
configuration:
    - Debug
    - Release
platform:
    - x86
    - Any CPU
matrix:
    fast_finish: false
