version: '1.0.{build}'
install:
    - mkdir build
    - cd build
    - if ["%platform%"] == ["x64"] cmake -G "Visual Studio 14 2015 Win64" ..
    - if ["%platform%"] == ["Win32"] cmake -G "Visual Studio 14 2015" ..
    - cd ..
build_script:
    - msbuild "build/Demo.sln"
test_script:
    - cd build
    - ctest
    - cd ..
branches:
    except:
        - gh-pages
configuration:
    - Debug
    - Release
platform:
    - Win32
    - x64
matrix:
    fast_finish: false
build:
    parallel: true                          # enable MSBuild parallel builds
    project: "build/Demo.sln"    # path to Visual Studio solution or project
