version: '1.0.{build}'
install:
    - mkdir build
    - cd build
    - cmake ..
    - cd ..
build_script:
    - msbuild "build//DEFAULT_PROJECT.sln" /p:Configuration=Debug /p:Platform=x86
branches:
    except:
        - gh-pages
configuration:
    - Debug
    - Release
platform:
    - x86
    - Win32
    - Any CPU
matrix:
    fast_finish: false
build:
    parallel: true                          # enable MSBuild parallel builds
    project: "build/DEFAULT_PROJECT.sln"    # path to Visual Studio solution or project
